services:
  - type: web
    name: autochord-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
  - type: web
    name: autochord-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: autochord-postgres
          property: connectionString
      - key: PORT
        value: 4000

databases:
  - name: autochord-postgres
    plan: free
    databaseName: autochord
    user: autochord_user
